---
- name: Hello World!
  hosts: all
  user: dylan_kao
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi!  AWX is working"
    sudo: yes
    
  - name: install mysql
    yum: name=mysql state=latest
    sudo: yes
