---

- name: isntall My SQL
  hosts: all
  user: dylan_kao
 
  tasks:
  
- name: Hello World!
  shell: echo "Hi!  AWX is working"
  sudo: yes
 
- name: Install the latest version of MySQL
  yum: name=mysql state=latest
  sudo: yes
